
# Where things are
source:       .
destination:  ./_site
# plugins:      ./_plugins
# layouts:      ./_layouts
paginate: 10
paginate_path: "page:num"
gems: [jekyll-paginate]
# Handling Reading
include:      [".htaccess"]
exclude:      ["node_modules", "package.json", "gulpfile.js"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Conversion
lsi:          false
excerpt_separator: "\n\n\n"

# Serving
detach:       false
port:         3000
host:         127.0.0.1
url:          /blog-jekyll
cloudSrc:     "http://7xrioc.com1.z0.glb.clouddn.com"

#################################### global configure #######################################


baseurl: /blog-jekyll
markdown: kramdown

safe: false
highlighter: rouge
title: 莫忘初衷
description: 莫忘初衷，不负此生。
theme: slate
github_username:  love-peach
disqusname: DoubleLord
