
# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Conversion
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
url:          /blog-jekyll

#################################### global configure #######################################

baseurl: /blog-jekyll
markdown: redcarpet
safe: false
highlighter: pygments
title: 莫忘初衷
description: 莫忘初衷，不负此生。
theme: slate
github_username:  love-peach
disqusname: DoubleLord
