# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  这里是网站的描述.
baseurl: "/blog-jekyll" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

highlighter: pygments
github: [Repository metadata]
safe: true
lsi: false


github_username:  love-peach

# Build settings
markdown: kramdown
